/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSharedWithMeRouteImport } from './routes/_app/shared-with-me'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppNotesNewIndexRouteImport } from './routes/_app/notes/new/index'
import { Route as AppNotesNewPreviewRouteImport } from './routes/_app/notes/new/preview'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppSharedWithMeRoute = AppSharedWithMeRouteImport.update({
  id: '/shared-with-me',
  path: '/shared-with-me',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesNewIndexRoute = AppNotesNewIndexRouteImport.update({
  id: '/notes/new/',
  path: '/notes/new/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesNewPreviewRoute = AppNotesNewPreviewRouteImport.update({
  id: '/notes/new/preview',
  path: '/notes/new/preview',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/explore': typeof AppExploreRoute
  '/shared-with-me': typeof AppSharedWithMeRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/notes/new/preview': typeof AppNotesNewPreviewRoute
  '/notes/new': typeof AppNotesNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/explore': typeof AppExploreRoute
  '/shared-with-me': typeof AppSharedWithMeRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/notes/new/preview': typeof AppNotesNewPreviewRoute
  '/notes/new': typeof AppNotesNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/shared-with-me': typeof AppSharedWithMeRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/notes/new/preview': typeof AppNotesNewPreviewRoute
  '/_app/notes/new/': typeof AppNotesNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/shared-with-me'
    | '/login'
    | '/register'
    | '/notes/new/preview'
    | '/notes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/shared-with-me'
    | '/login'
    | '/register'
    | '/notes/new/preview'
    | '/notes/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_app/explore'
    | '/_app/shared-with-me'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/notes/new/preview'
    | '/_app/notes/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/shared-with-me': {
      id: '/_app/shared-with-me'
      path: '/shared-with-me'
      fullPath: '/shared-with-me'
      preLoaderRoute: typeof AppSharedWithMeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notes/new/': {
      id: '/_app/notes/new/'
      path: '/notes/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof AppNotesNewIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notes/new/preview': {
      id: '/_app/notes/new/preview'
      path: '/notes/new/preview'
      fullPath: '/notes/new/preview'
      preLoaderRoute: typeof AppNotesNewPreviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppExploreRoute: typeof AppExploreRoute
  AppSharedWithMeRoute: typeof AppSharedWithMeRoute
  AppNotesNewPreviewRoute: typeof AppNotesNewPreviewRoute
  AppNotesNewIndexRoute: typeof AppNotesNewIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppExploreRoute: AppExploreRoute,
  AppSharedWithMeRoute: AppSharedWithMeRoute,
  AppNotesNewPreviewRoute: AppNotesNewPreviewRoute,
  AppNotesNewIndexRoute: AppNotesNewIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
