version: "3.9"

services:
    web-frontend:
        build:
            context: .
            dockerfile: Dockerfile
        image: cbx-notes-suite-frontend:latest
        container_name: cbx-notes-suite-frontend
        ports:
            - "3000:3000"
        restart: unless-stopped
        environment:
            - VITE_API_URL=http://localhost:8080
            - VITE_ENVIRONMENT=prod
